config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root 'welcome#index'
  
  resources :categories, except: [:destroy]

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :image_categories #MTM ASSOCIATION
  has_many :categories, through: :image_categories #MTM ASSOCIATION
  mount_uploader :picture, PictureUploader
  validate :picture_size
  validates :name, presence: true, length: { minimum: 3, maximum: 24 }
  validates :category_ids, presence: true
  validates :picture, presence: true

  private

  def picture_size
    if picture.size > 5.megabytes
      erros.add(:picture, "Should be not greater than 5MB")
    end
  end


end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  #before_action :require_user, except: [:show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    #@images = Image.all
    @images = current_user.images.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :tag, :picture, :user_id, category_ids: [])
    end

#     def require_user
#       if current_user != @images.user
#         flash[:danger] = "You can view your own image collections!"
#         redirect_to root_path
#       end
#     end

    def require_same_user
      if current_user != @image.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own images!"
        redirect_to root_path
      end
    end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, :html => { multipart: true, :class => "form-horizontal image" } do |f| %>

  <% if @image.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%#=f.error_span(:name) %>
  </div>
  <!-- Tag -->
  <div class="form-group">
    <%= f.label :tag, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tag, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tag) %>
  </div>
  <!-- Tag End -->
  <div class="form-group">
    <%= f.label :picture, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </div>
    <%#=f.error_span(:picture) %>
  </div>
  <!-- Category -->
  <div class="form-group">
    <%= f.label :category, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>
    <%#=f.error_span(:category) %>
  </div>
  <!-- Category End -->


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                images_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  $('#image_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB!');
    }
  });
</script>

app/views/images/_image.html.erb
<% obj.each do |i| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to i.name, image_path(i) %><br /><br />T


          <%= image_tag(i.picture.url, size: "250x250") if i.picture? %>



        </div>
        <div class="article-body">
          <%= truncate(i.tag, length: 95) %>
          <div class="article-meta-details">
            <small>Published by: <%= i.user.email if i.user_id  %>,
                  <%= time_ago_in_words(i.created_at) %> ago,
                  last updated: <%= time_ago_in_words(i.updated_at) %> ago</small>
          </div>
        </div>

        <% if user_signed_in? && (current_user == i.user || current_user.admin?) %>
          <div class="aricle-actions">
            <%= link_to "Edit this image", edit_image_path(i), class: "btn btn-xs btn primary" %>
          </div>
        <% end %>


        <% if i.categories.any? %>
          <p>Categories: <%= render i.categories %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %> Z</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:tag) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image.name, image_path(image) %></td>
        <td><%= link_to (image_tag image.picture.url, size: "100x100"), image_path(image) %></td>
        <td><%= image.tag %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_image_path(image), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      image_path(image),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_image_path,
            :class => 'btn btn-primary' %>

app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/show.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @image.name %></dd>
  <dd></dd>
  <dt><strong><%= model_class.human_attribute_name(:tag) %>:</strong></dt>
  <dd><%= @image.tag %></dd>
  <dd></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= render @image.categories %></dd>
  <dd></dd>
  <dd><%= image_tag(@image.picture.url, size: "250x250") if @image.picture? %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              images_path, :class => 'btn btn-default'  %>

<% if user_signed_in? && (current_user == @image.user || current_user.admin?) %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_image_path(@image), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              image_path(@image),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>